### ISSUE TITLE
Limit reached after 2 failed call drops

### ISSUE THREAD

**Issue by bajajsahil** [truecaller/flutter-sdk#10]
Hi,

I was testing the verification and found after 2 failed call drops, I am getting the below error:

"**2 : Invalid verification status: Phone number limit reached**"

If I put the other phone number, then I am getting the below error:

"**2 : Invalid verification status: Request id limit reached**"

So, ideally, we should get the OTP verification in case of missed call verification failed. And, what is the time limit for retrying verification after the above errors?

**Comment by singhalyogesh** [comment]
**Invalid verification status: Phone number limit reached** : You get this error when you have exhausted the verification limit allowed on a particular number

**Invalid verification status: Request id limit reached** : This error comes when you have exhausted the verification limits allowed on a particular device.

If you receive the above errors during testing, the limit gets auto reset after 24 hours.

**Comment by bajajsahil** [comment]
Thanks @singhalyogesh for the answers.

But, in which case or at what point I should expect the OTP verification? Because I tried multiple times but every time it is missed call. As currently, we are developing so we need to test the OTP verification also.

**Comment by singhalyogesh** [comment]
@bajajsahil  You would receive an OTP if you deny the phone permissions needed for drop call flow

**Comment by bajajsahil** [comment]
Thanks @singhalyogesh. It worked.

One last question - is there any way I can delete the verification data from the device so that I don't get the ```verifiedBefore``` event?

**Comment by singhalyogesh** [comment]
@bajajsahil You can send us the testing mobile number you are using during development phase. We can whitelist your number at our end to prevent it from going into "verified before" state to help you test out the verification scenarios. Please raise a ticket with your app details and testing number here ( https://developer.truecaller.com/contact ) with the query type as "Technical Integration"

**Comment by bajajsahil** [comment]
Awesome. Thanks @singhalyogesh.
