### ISSUE TITLE
SDK crash in production

### ISSUE THREAD

**Issue by Amitpatil215** [truecaller/flutter-sdk#17]
Hi, @parth0907
I have attached logs and MainActivity,kt file. Please have a look. Its possibly related to truecaller sdk. Can you please guide us what causing this issue?

#### Stack trace from firebase crashlytics
<details>
<summary>Logs</summary>

```
com.truecaller.android.sdk.TruecallerSDK.onActivityResultObtained (TruecallerSDK.java:34)
dipinarora9.flutter_truecaller.FlutterTruecallerPlugin$onAttachedToActivity$1.onActivityResult (FlutterTruecallerPlugin.java:31)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult (FlutterEngineConnectionRegistry.java:25)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult (FlutterEngineConnectionRegistry.java:15)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult (FlutterActivityAndFragmentDelegate.java:51)
io.flutter.embedding.android.FlutterFragment.onActivityResult (FlutterFragment.java:10)
io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult (FlutterFragmentActivity.java:5)

```

android.app.Activity.dispatchActivityResult (Activity.java:7762)
android.app.ActivityThread.deliverResults (ActivityThread.java:4603)
android.app.ActivityThread.handleSendResult (ActivityThread.java:4652)
android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:49)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1948)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7050)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)

</details>

#### MainActivity.kt file

<details>
<summary>file</summary>

```
package com.theclosecompany.sales_book

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant
import com.facebook.FacebookSdk;

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}

```

</details>

**Comment by parth0907** [comment]
Hi @Amitpatil215 , 

Thanks for writing in! 

We investigated the logs and suspect that you are using a third party flutter plugin to integrate truecallerSDK. I would request you to use our official flutter plugin. Please find attached our official flutter package [here](https://pub.dev/packages/flutter_truecaller) 

In case of any further questions regarding the documentation, please feel free to reach us via our support channel https://developer.truecaller.com/support for a faster and dedicated response. 

Regards,
Parth

**Comment by Amitpatil215** [comment]
Thanks, appreciating your time and effort.
