### ISSUE TITLE
truecaller flutter sdk not import

### ISSUE THREAD

**Issue by yogeshkaharmis** [truecaller/flutter-sdk#50]
hello 
I am integrate true caller flutter sdk in project but i am getting all time below error

ERROR:C:\Users\Android\.gradle\caches\transforms-3\2e6db0ffe72e20ef42d225fd3593282a\transformed\jetified-truecaller-sdk-3.0.0-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes

how to solve issue.
thanks you.

**Comment by vedha1017** [comment]
I also faced that issue, I solved that using a lower sdk version (https://pub.dev/packages/truecaller_sdk/versions/0.1.2)

**Comment by yogeshkaharmis** [comment]
hello
i also using lower SDK version but data will not come so I am getting Invalid partner credentials error on truecaller flutter sdk using in project.
