### ISSUE TITLE
Issue with Java Code

### ISSUE THREAD

**Issue by vishalsaini9** [truecaller/flutter-sdk#8]
PlatformException(error, com.abc.MainActivity cannot be cast to androidx.fragment.app.FragmentActivity, null, java.lang.ClassCastException: com.abc..MainActivity cannot be cast to androidx.fragment.app.FragmentActivity

How to resolve it on a Java-based project?

**Comment by vishalsaini9** [comment]
**PlatformException(error, com.abc.MainActivity cannot be cast to androidx.fragment.app.FragmentActivity, null, java.lang.ClassCastException: com.abc..MainActivity cannot be cast to androidx.fragment.app.FragmentActivity

How to resolve it on a Java-based project?**

**Comment by shubhral** [comment]
Doesn't matter if you're using Java instead of Kotlin, you still need to extend your activity with **FlutterFragmentActivity** in your Flutter project as mentioned in [Step 3](https://github.com/truecaller/flutter-sdk/blob/master/README.md)

So your activity in Java should be like this - 

```java
public class MainActivity extends FlutterFragmentActivity {
    @Override
    public void configureFlutterEngine(@NonNull final FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
